name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format:check

  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dummy-server dependencies
        run: npm ci
        working-directory: dummy-server

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npm run test

  copy-verify:
    name: Copy & Verify Outputs
    runs-on: ubuntu-latest
    needs: test-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Copy library
        run: |
          rm -rf lib/configressif
          mkdir -p lib
          cp -r workbench/lib/configressif lib/

      - name: Copy frontend output
        run: |
          rm -rf data
          cp -r workbench/data data

      - name: Verify files copied
        run: |
          test -f data/public/index.html
          test -d data/assets
          test -f lib/configressif/src/configressif.h
